import { BASE_URL } from './utils/BASE_URL';

/**
 * Auto-generated EventSource client
 * Generated by StateleSSE.CodeGen.Typescript NuGet package
 * DO NOT EDIT MANUALLY
 */

/**
 * Subscribe to RoundStartedEvent events
 * @param gameid - GameId
 * @returns EventSource instance for RoundStartedEvent
 */
export function streamRoundStarted(gameid: string): EventSource {
    const queryParams = new URLSearchParams({ gameid });
    const url = `${BASE_URL}/RoundStartedEvent?${queryParams}`;
    return new EventSource(url);
}

/**
 * Subscribe to PlayerJoinedEvent events
 * @param gameid - GameId
 * @returns EventSource instance for PlayerJoinedEvent
 */
export function streamPlayerJoined(gameid: string): EventSource {
    const queryParams = new URLSearchParams({ gameid });
    const url = `${BASE_URL}/PlayerJoinedEvent?${queryParams}`;
    return new EventSource(url);
}

/**
 * Subscribe to AnswerSubmittedEvent events
 * @param gameid - GameId
 * @returns EventSource instance for AnswerSubmittedEvent
 */
export function streamAnswerSubmitted(gameid: string): EventSource {
    const queryParams = new URLSearchParams({ gameid });
    const url = `${BASE_URL}/AnswerSubmittedEvent?${queryParams}`;
    return new EventSource(url);
}

/**
 * Subscribe to RoundEndedEvent events
 * @param gameid - GameId
 * @returns EventSource instance for RoundEndedEvent
 */
export function streamRoundEnded(gameid: string): EventSource {
    const queryParams = new URLSearchParams({ gameid });
    const url = `${BASE_URL}/RoundEndedEvent?${queryParams}`;
    return new EventSource(url);
}

/**
 * Subscribe to GameCreatedEvent events
 * @param gameid - GameId
 * @returns EventSource instance for GameCreatedEvent
 */
export function streamGameCreated(gameid: string): EventSource {
    const queryParams = new URLSearchParams({ gameid });
    const url = `${BASE_URL}/GameCreatedEvent?${queryParams}`;
    return new EventSource(url);
}

/**
 * Generic EventSource helper with typed callbacks
 */
export function createTypedEventStream<T>(
    url: string,
    onMessage: (event: T) => void,
    onError?: (error: Event) => void
): EventSource {
    const es = new EventSource(url);

    es.onmessage = (e) => {
        try {
            const data: T = JSON.parse(e.data);
            onMessage(data);
        } catch (error) {
            console.error('Failed to parse SSE event:', error);
        }
    };

    if (onError) {
        es.onerror = onError;
    }

    return es;
}
