//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class KahootGameClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    login(dto: AuthRequestDto): Promise<JwtResponse> {
        let url_ = this.baseUrl + "/Login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<JwtResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as JwtResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<JwtResponse>(null as any);
    }

    register(dto: AuthRequestDto): Promise<JwtResponse> {
        let url_ = this.baseUrl + "/Register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<JwtResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as JwtResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<JwtResponse>(null as any);
    }

    getQuizzes(): Promise<QuizReturnDto[]> {
        let url_ = this.baseUrl + "/GetQuizzes";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetQuizzes(_response);
        });
    }

    protected processGetQuizzes(response: Response): Promise<QuizReturnDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as QuizReturnDto[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<QuizReturnDto[]>(null as any);
    }

    getQuiz(quizId: string | undefined): Promise<QuizReturnDto> {
        let url_ = this.baseUrl + "/GetQuiz?";
        if (quizId === null)
            throw new globalThis.Error("The parameter 'quizId' cannot be null.");
        else if (quizId !== undefined)
            url_ += "quizId=" + encodeURIComponent("" + quizId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetQuiz(_response);
        });
    }

    protected processGetQuiz(response: Response): Promise<QuizReturnDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as QuizReturnDto;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<QuizReturnDto>(null as any);
    }

    gameStream(gameId: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/GameStream?";
        if (gameId === null)
            throw new globalThis.Error("The parameter 'gameId' cannot be null.");
        else if (gameId !== undefined)
            url_ += "gameId=" + encodeURIComponent("" + gameId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGameStream(_response);
        });
    }

    protected processGameStream(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    getSseEventTypes(): Promise<GameEventUnion> {
        let url_ = this.baseUrl + "/__internal/sse-event-types";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSseEventTypes(_response);
        });
    }

    protected processGetSseEventTypes(response: Response): Promise<GameEventUnion> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as GameEventUnion;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GameEventUnion>(null as any);
    }

    createGame(request: CreateGameRequest): Promise<CreateGameResponse> {
        let url_ = this.baseUrl + "/CreateGame";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateGame(_response);
        });
    }

    protected processCreateGame(response: Response): Promise<CreateGameResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CreateGameResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CreateGameResponse>(null as any);
    }

    joinGame(request: JoinGameRequest): Promise<JoinGameResponse> {
        let url_ = this.baseUrl + "/JoinGame";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processJoinGame(_response);
        });
    }

    protected processJoinGame(response: Response): Promise<JoinGameResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as JoinGameResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<JoinGameResponse>(null as any);
    }

    startRound(request: StartRoundRequest): Promise<StartRoundResponse> {
        let url_ = this.baseUrl + "/StartRound";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStartRound(_response);
        });
    }

    protected processStartRound(response: Response): Promise<StartRoundResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as StartRoundResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<StartRoundResponse>(null as any);
    }

    submitAnswer(request: SubmitAnswerRequest): Promise<SubmitAnswerResponse> {
        let url_ = this.baseUrl + "/SubmitAnswer";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSubmitAnswer(_response);
        });
    }

    protected processSubmitAnswer(response: Response): Promise<SubmitAnswerResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as SubmitAnswerResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubmitAnswerResponse>(null as any);
    }

    endRound(request: EndRoundRequest): Promise<EndRoundResponse> {
        let url_ = this.baseUrl + "/EndRound";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processEndRound(_response);
        });
    }

    protected processEndRound(response: Response): Promise<EndRoundResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as EndRoundResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<EndRoundResponse>(null as any);
    }

    getGameState(gameId: string | undefined): Promise<GameStateResponse> {
        let url_ = this.baseUrl + "/GetGameState?";
        if (gameId === null)
            throw new globalThis.Error("The parameter 'gameId' cannot be null.");
        else if (gameId !== undefined)
            url_ += "gameId=" + encodeURIComponent("" + gameId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetGameState(_response);
        });
    }

    protected processGetGameState(response: Response): Promise<GameStateResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as GameStateResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GameStateResponse>(null as any);
    }
}

export class GameEventsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    streamRoundStarted(gameId: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/RoundStartedEvent?";
        if (gameId === null)
            throw new globalThis.Error("The parameter 'gameId' cannot be null.");
        else if (gameId !== undefined)
            url_ += "GameId=" + encodeURIComponent("" + gameId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStreamRoundStarted(_response);
        });
    }

    protected processStreamRoundStarted(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    streamPlayerJoined(gameId: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/PlayerJoinedEvent?";
        if (gameId === null)
            throw new globalThis.Error("The parameter 'gameId' cannot be null.");
        else if (gameId !== undefined)
            url_ += "GameId=" + encodeURIComponent("" + gameId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStreamPlayerJoined(_response);
        });
    }

    protected processStreamPlayerJoined(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    streamAnswerSubmitted(gameId: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/AnswerSubmittedEvent?";
        if (gameId === null)
            throw new globalThis.Error("The parameter 'gameId' cannot be null.");
        else if (gameId !== undefined)
            url_ += "GameId=" + encodeURIComponent("" + gameId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStreamAnswerSubmitted(_response);
        });
    }

    protected processStreamAnswerSubmitted(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    streamRoundEnded(gameId: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/RoundEndedEvent?";
        if (gameId === null)
            throw new globalThis.Error("The parameter 'gameId' cannot be null.");
        else if (gameId !== undefined)
            url_ += "GameId=" + encodeURIComponent("" + gameId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStreamRoundEnded(_response);
        });
    }

    protected processStreamRoundEnded(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    streamGameCreated(gameId: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/GameCreatedEvent?";
        if (gameId === null)
            throw new globalThis.Error("The parameter 'gameId' cannot be null.");
        else if (gameId !== undefined)
            url_ += "GameId=" + encodeURIComponent("" + gameId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStreamGameCreated(_response);
        });
    }

    protected processStreamGameCreated(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface JwtResponse {
    token?: string;
}

export interface AuthRequestDto {
    name: string;
    password: string;
}

export interface QuizReturnDto {
    id?: string;
    name?: string;
    createdby?: string;
    createdbyNavigation?: UserReturnDto | undefined;
    totalQuestions?: number;
}

export interface UserReturnDto {
    id?: string;
    name?: string;
}

export interface GameEventUnion {
    type?: string;
    gameCreated?: GameCreatedEvent | undefined;
    playerJoined?: PlayerJoinedEvent | undefined;
    roundStarted?: RoundStartedEvent | undefined;
    answerSubmitted?: AnswerSubmittedEvent | undefined;
    roundEnded?: RoundEndedEvent | undefined;
    gameState?: SseEventEnvelopeOfGameStateResponse | undefined;
}

export interface GameCreatedEvent {
    gameId?: string;
    quizName?: string;
    hostId?: string;
    questionCount?: number;
    timestamp?: string;
    type?: string;
}

export interface PlayerJoinedEvent {
    userId?: string;
    userName?: string;
    playerCount?: number;
    timestamp?: string;
    type?: string;
}

export interface RoundStartedEvent {
    roundId?: string;
    questionId?: string;
    questionText?: string;
    timeLimit?: number;
    options?: QuestionOptionInfo[];
    timestamp?: string;
    type?: string;
}

export interface QuestionOptionInfo {
    id?: string;
    text?: string;
}

export interface AnswerSubmittedEvent {
    userId?: string;
    answersReceived?: number;
    timestamp?: string;
    type?: string;
}

export interface RoundEndedEvent {
    roundId?: string;
    correctOptionId?: string;
    results?: RoundResultEntry[];
    leaderboard?: LeaderboardEntry[];
    timestamp?: string;
    type?: string;
}

export interface RoundResultEntry {
    userId?: string;
    userName?: string;
    optionId?: string;
    isCorrect?: boolean;
    answeredAt?: string | undefined;
}

export interface LeaderboardEntry {
    userId?: string;
    userName?: string;
    score?: number;
}

export interface SseEventEnvelopeOfGameStateResponse {
    type?: string;
    data?: GameStateResponse | undefined;
}

export interface GameStateResponse {
    gameId?: string;
    quizName?: string;
    hostName?: string;
    players?: PlayerInfo[];
    currentRound?: CurrentRoundInfo | undefined;
    leaderboard?: LeaderboardEntry[];
    totalRounds?: number;
}

export interface PlayerInfo {
    userId?: string;
    userName?: string;
    joinedAt?: string;
}

export interface CurrentRoundInfo {
    roundId?: string;
    questionText?: string;
    timeLimit?: number;
    options?: QuestionOptionInfo[];
    startedAt?: string;
}

export interface CreateGameResponse {
    gameId?: string;
    quizName?: string;
    questionCount?: number;
}

export interface CreateGameRequest {
    quizId?: string;
    hostUserId?: string;
}

export interface JoinGameResponse {
    status?: string;
    gameId?: string;
    playerCount?: number;
}

export interface JoinGameRequest {
    gameId?: string;
    userId?: string;
}

export interface StartRoundResponse {
    roundId?: string;
    status?: string;
}

export interface StartRoundRequest {
    gameId?: string;
    questionId?: string;
}

export interface SubmitAnswerResponse {
    status?: string;
    isCorrect?: boolean;
}

export interface SubmitAnswerRequest {
    gameId?: string;
    roundId?: string;
    userId?: string;
    optionId?: string;
}

export interface EndRoundResponse {
    status?: string;
    results?: RoundResultEntry[];
    leaderboard?: LeaderboardEntry[];
}

export interface EndRoundRequest {
    gameId?: string;
    roundId?: string;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}