import { BASE_URL } from './utils/BASE_URL';
import type { Message } from './generated-client.ts';

/**
 * Auto-generated EventSource client
 * Generated by StateleSSE.CodeGen
 * DO NOT EDIT MANUALLY
 */

/**
 * Subscribe to Message events
 * @param groupId - groupId (optional)
 * @param onMessage - Callback for typed message events
 * @param onError - Optional error callback
 * @returns EventSource instance for Message
 */
export function streamMessages(groupId?: string, onMessage?: (event: Message) => void, onError?: (error: Event) => void): EventSource {
    const queryParams = new URLSearchParams({ ...(groupId !== undefined ? { 'groupId': groupId } : {}) });
    const url = `${BASE_URL}/StreamMessages?${queryParams}`;
    
    const es = new EventSource(url);
    
    if (onMessage) {
        es.onmessage = (e) => {
            try {
                const data: Message = JSON.parse(e.data);
                onMessage(data);
            } catch (error) {
                console.error('Failed to parse SSE event:', error);
            }
        };
    }
    
    if (onError) {
        es.onerror = onError;
    }
    
    return es;
}

