/* eslint-disable */
// @ts-nocheck

import { BASE_URL } from './utils/BASE_URL';
import type { Message } from './generated-client.ts';

/**
 * Auto-generated EventSource client
 * Generated by StateleSSE.CodeGen
 * DO NOT EDIT MANUALLY
 */

/**
 * Subscribe to Message events
 * @param groupId - groupId (optional)
 * @param onMessage - Callback for typed message events
 * @param onError - Optional error callback. Triggered on connection errors, network failures, or when server closes the connection
 * @returns EventSource instance for Message
 */
export function streamMessages(groupId?: string, onMessage?: (event: Message) => void, onError?: (error: Event) => void): EventSource {
    const queryParams = new URLSearchParams({ ...(groupId !== undefined ? { 'groupId': groupId } : {}) });
    const url = `${BASE_URL}/StreamMessages?${queryParams}`;
    
    const es = new EventSource(url);
    
    if (onMessage) {
        es.onmessage = (e) => {
            try {
                const data: Message = JSON.parse(e.data);
                onMessage(data);
            } catch (error) {
                console.error('Failed to parse SSE event:', error);
            }
        };
    }
    
    if (onError) {
        es.onerror = onError;
    }
    
    return es;
}

/**
 * Generic version of streamMessages that accepts any parameters and returns any type
 * Use this for custom scenarios where you need full control over types
 * @param params - Query parameters as any object
 * @param onMessage - Callback for typed message events
 * @param onError - Optional error callback. Triggered on connection errors, network failures, or when server closes the connection
 * @returns EventSource instance
 */
export function streamMessagesGeneric<T = any>(params?: any, onMessage?: (event: T) => void, onError?: (error: Event) => void): EventSource {
    const queryParams = params ? new URLSearchParams(params) : new URLSearchParams();
    const url = `${BASE_URL}/StreamMessages?${queryParams}`;
    
    const es = new EventSource(url);
    
    if (onMessage) {
        es.onmessage = (e) => {
            try {
                const data: T = JSON.parse(e.data);
                onMessage(data);
            } catch (error) {
                console.error('Failed to parse SSE event:', error);
            }
        };
    }
    
    if (onError) {
        es.onerror = onError;
    }
    
    return es;
}

