import { BASE_URL } from './utils/BASE_URL';

/**
 * Auto-generated EventSource client
 * Generated by StateleSSE.CodeGen
 * DO NOT EDIT MANUALLY
 */

/**
 * Subscribe to Message events
 * @param groupid - groupId (optional)
 * @param onMessage - Callback for typed message events
 * @param onError - Optional error callback
 * @returns EventSource instance for Message
 */
export function streamMessages<T = any>(
    onMessage: (event: T) => void, 
    groupid?: string,
    onError?: (error: Event) => void
): EventSource {
    const queryParams = new URLSearchParams({ ...(groupid !== undefined ? { groupid } : {}) });
    const url = `${BASE_URL}/StreamMessages?${queryParams}`;
    
    const es = new EventSource(url);
    es.onmessage = (e) => {
        try {
            const data: T = JSON.parse(e.data);
            onMessage(data);
        } catch (error) {
            console.error('Failed to parse SSE event:', error);
        }
    };
    
    if (onError) {
        es.onerror = onError;
    }
    
    return es;
}

