export const styles: Record<string, React.CSSProperties> = {
    loginContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100vh',
        gap: '1rem',
        fontFamily: 'system-ui, sans-serif',
    },
    input: {
        padding: '0.75rem 1rem',
        fontSize: '1rem',
        border: '1px solid #ccc',
        borderRadius: '4px',
        width: '250px',
    },
    button: {
        padding: '0.75rem 1.5rem',
        fontSize: '1rem',
        backgroundColor: '#007bff',
        color: 'white',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
    },
    chatContainer: {
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        fontFamily: 'system-ui, sans-serif',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '1rem',
        borderBottom: '1px solid #eee',
        backgroundColor: '#f8f9fa',
    },
    connectionStatus: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        fontSize: '0.875rem',
        color: '#666',
    },
    statusDot: {
        width: '8px',
        height: '8px',
        borderRadius: '50%',
    },
    connectionId: {
        fontSize: '0.75rem',
        color: '#999',
        fontFamily: 'monospace',
    },
    mainContent: {
        display: 'flex',
        flex: 1,
        overflow: 'hidden',
    },
    sidebar: {
        width: '200px',
        borderRight: '1px solid #eee',
        padding: '1rem',
        backgroundColor: '#fafafa',
    },
    chatMain: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
    },
    messageList: {
        flex: 1,
        overflow: 'auto',
        padding: '1rem',
    },
    emptyState: {
        color: '#999',
        fontStyle: 'italic',
        textAlign: 'center',
        padding: '2rem',
    },
    message: {
        marginBottom: '0.75rem',
        padding: '0.5rem',
        backgroundColor: '#f0f0f0',
        borderRadius: '4px',
    },
    author: {
        color: '#007bff',
        marginRight: '0.5rem',
    },
    content: {
        color: '#333',
    },
    timestamp: {
        fontSize: '0.75rem',
        color: '#999',
        marginLeft: '0.5rem',
    },
    typingIndicator: {
        padding: '0.5rem 1rem',
        fontSize: '0.875rem',
        color: '#666',
        fontStyle: 'italic',
    },
    onlineUsers: {
        fontSize: '0.875rem',
    },
    userList: {
        listStyle: 'none',
        padding: 0,
        margin: 0,
    },
    userItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        padding: '0.25rem 0',
    },
    onlineDot: {
        width: '8px',
        height: '8px',
        borderRadius: '50%',
        backgroundColor: '#4caf50',
    },
    inputContainer: {
        display: 'flex',
        gap: '0.5rem',
        padding: '1rem',
        borderTop: '1px solid #eee',
    },
    messageInput: {
        flex: 1,
        padding: '0.75rem',
        fontSize: '1rem',
        border: '1px solid #ccc',
        borderRadius: '4px',
    },
    sendButton: {
        padding: '0.75rem 1.5rem',
        fontSize: '1rem',
        backgroundColor: '#007bff',
        color: 'white',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
    },
};